language: php
dist: trusty
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
install:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then composer require satooshi/php-coveralls '~1.0'; fi
  - composer install --prefer-dist
matrix:
  allow_failures:
    - php: nightly
    - php: 7.0
  fast_finish: true